### ISSUE TITLE
Aggregate Tiling

### ISSUE THREAD

**Issue by retallickj** [siqad/siqad#29]
To make arrays of devices, we should add something like the following:

- When the user selects an Aggregate/Item and presses D (or some other key combo) in DB creation mode, a prompt comes up like "Count: <QSpinBox>".
- User types in the number of copies they want to make. Make sure up and down arrows work and the focus automatically jump to the entry field: i.e. typing a number after D automatically fills the QSpinBox.
- When the user presses enter, a Ghost is created containing the given number of copies of the selected Aggregate/Item. We will have to change Ghost so that it shows a number of copies of the item offset by some delta lattice coordinate.
- The user indicates the spacing in the array by where they click next, with the Ghost showing the projected positions of the array.

**Comment by samuelngsh** [comment]
Closing since you've implemented it long ago.
