### ISSUE TITLE
External simulation support

### ISSUE THREAD

**Issue by NathanChiu** [siqad/siqad#37]
Having an external simulator as a simulation option can be reassuring for users, and might help with the initial buy-in of SiQAD. 

1. Simulation file generation
    * Output a file that allows SiQAD's designs to be simulated using COMSOL/ANSYS.

2. Direct integration
    * Directly call the external tool from the simulations dialog in SiQAD.

3. Calibration of our own electrostatics simulations to external tools.
    *Tune our simulations for USE, Feedforward clocking networks to match COMSOL/ANSYS results of the same networks.

**Comment by samuelngsh** [comment]
@NathanChiu,

From my understanding, the design files used in COMSOL simulations in your thesis were created separately in COMSOL right?

Is it remotely trivial to perform the conversion noted in point 1? If not, then I'd say let's close this unless there's internal demand.

**Comment by samuelngsh** [comment]
Closing until there exists further demand for this.
