### ISSUE TITLE
Seg Fault when trying to create clip area with a loaded design

### ISSUE THREAD

**Issue by retallickj** [siqad/siqad#68]
Last line of log:
Warning: "Layer index -1 out of bounds..."

**Comment by samuelngsh** [comment]
Try the version from the latest dev branch

**Comment by samuelngsh** [comment]
To be specific, this issue should have been fixed in commit 3c2e481116d2662149325d953f9e9c1ff848e328.

Please re-open the issue if it still doesn't work.
